language: php

php:
  - 5.5

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - php vendor/bin/coveralls -v
